MixMixMVC/MixMixMVC/Models/DrinkDecriptionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MixMixMVC.Models
{
    public class DrinkDecriptionViewModel
    {
        public string Recipe { get; set; }
    }
}

MixMixMVC/MixMixMVC/Models/DrinkIngredientViewModel.cs
using MixMixMVC.DrinkServiceReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MixMixMVC.Models
{
    public class DrinkIngredientViewModel
    {
        public string Ingredient { get; set; }
        public string Measurement { get; set; }
        public double Quantity { get; set; }
        public List<Ingredient> Ingredients { get; set; }
        public List<Measurement> Measurements { get; set; }
        public int BarId { get; set; }
        public string DrinkName { get; set; }
        public List<QuantifiedIngredient> QuantifiedIngredients { get; set; }
    }
}

MixMixMVC/MixMixMVC/Models/DrinkNameViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MixMixMVC.Models
{
    public class DrinkNameViewModel
    {
        [DisplayName("Drink navn")]
        public string DrinkName { get; set; }
    }
}

MixMixMVC/MixMixMVC/Controllers/DrinkController.cs
using MixMixMVC.Models;
using MixMixMVC.CustomerServiceReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MixMixMVC.BarServiceRerefence;
using MixMixMVC.DrinkServiceReference;
using MixMixMVC.Helpers;

namespace MixMixMVC.Controllers
{
    public class DrinkController : Controller
    {
        // GET: Drink
        [AuthorizedLogin]
        public ActionResult Index(int barId, string message)
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                DrinkServiceClient drinkProxy = serviceHelper.GetDrinkServiceClient();
                BarServiceClient barProxy = serviceHelper.GetBarServiceClient();
                //Ambiguous reference her
                BarServiceRerefence.Bar foundBar = barProxy.Find(barId);
                DrinkServiceReference.Bar bar = new DrinkServiceReference.Bar();
                bar.ID = foundBar.ID;
                bar.Name = foundBar.Name;

                Dictionary<int, DrinkViewModel> drinks = drinkProxy.GetAvailableDrinks(bar);

                ViewBag.barId = barId;
                ViewBag.BarName = bar.Name;
                ViewBag.Message = message;


                return View(drinks);
            }
        }
        [AuthorizedLogin]
        public ActionResult DrinkName(int barId)
        {
            ViewBag.barId = barId;
            return View();
        }

        // POST: Drink/Create
        [HttpPost]
        [AuthorizedLogin]
        public ActionResult DrinkName(FormCollection collection, int barId)
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                DrinkServiceClient drinkProxy = serviceHelper.GetDrinkServiceClient();
                try
                {
                    string name = Convert.ToString(collection["DrinkName"]);
                    bool drinkNameExists = drinkProxy.CheckDrinkName(name);
                    if (drinkNameExists)
                    {
                        string message = "Drinken eksisterer allerede.";
                        return RedirectToAction("Index", new { barId = barId, message = message });
                    }

                    Session["createDrink"] = new DrinkIngredientViewModel();

                    ((DrinkIngredientViewModel)Session["createDrink"]).DrinkName = name;
                    ((DrinkIngredientViewModel)Session["createDrink"]).BarId = barId;

                    return RedirectToAction("DrinkIngredient");
                }
                catch
                {
                    string message = "Der skete desværre en fejl.";
                    return RedirectToAction("Index", new { barId = barId, message = message });
                }
            }
        }
        [AuthorizedLogin]
        public ActionResult DrinkIngredient()
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                DrinkServiceClient drinkProxy = serviceHelper.GetDrinkServiceClient();
                DrinkIngredientViewModel drinkIngredientViewModel = new DrinkIngredientViewModel();
                drinkIngredientViewModel.Ingredients = drinkProxy.FindAllIngredients().ToList();
                drinkIngredientViewModel.Measurements = drinkProxy.FindAllMeasurements().ToList();
                return View(drinkIngredientViewModel);
            }
        }

        // POST: Drink/Create
        [HttpPost]
        [AuthorizedLogin]
        public ActionResult DrinkIngredient(FormCollection collection)
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                DrinkServiceClient drinkProxy = serviceHelper.GetDrinkServiceClient();
                try
                {
                    double quantity = Convert.ToDouble(collection["Quantity"]);

                    int ingredientId = Convert.ToInt32(collection["ddlIngredient"]);
                    int measurementId = Convert.ToInt32(collection["ddlMeasurement"]);

                    DrinkServiceReference.Ingredient ingredient = new DrinkServiceReference.Ingredient();
                    ingredient = drinkProxy.FindIngredient(ingredientId);

                    DrinkServiceReference.Measurement measurement = new DrinkServiceReference.Measurement();
                    measurement = drinkProxy.FindMeasurement(measurementId);

                    DrinkServiceReference.QuantifiedIngredient quantifiedIngredient = new DrinkServiceReference.QuantifiedIngredient();
                    quantifiedIngredient.Ingredient = ingredient;
                    quantifiedIngredient.Measurement = measurement;
                    quantifiedIngredient.Quantity = quantity;

                    if (((DrinkIngredientViewModel)Session["createDrink"]).QuantifiedIngredients == null)
                    {
                        ((DrinkIngredientViewModel)Session["createDrink"]).QuantifiedIngredients = new List<DrinkServiceReference.QuantifiedIngredient>();
                    }

                ((DrinkIngredientViewModel)Session["createDrink"]).QuantifiedIngredients.Add(quantifiedIngredient);

                    return RedirectToAction("DrinkIngredient");
                }
                catch
                {
                    return View();
                }
            }
        }

        [AuthorizedLogin]
        public ActionResult DrinkDecription()
        {
            return View();
        }

        // POST: Drink/Create
        [HttpPost]
        [AuthorizedLogin]
        public ActionResult DrinkDecription(FormCollection collection)
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                DrinkServiceClient drinkProxy = serviceHelper.GetDrinkServiceClient();
                try
                {
                    DrinkServiceReference.Drink drink = new DrinkServiceReference.Drink();
                    drink.Ingredients = ((DrinkIngredientViewModel)Session["createDrink"]).QuantifiedIngredients.ToList();
                    drink.Names = new List<string> { ((DrinkIngredientViewModel)Session["createDrink"]).DrinkName };
                    drink.Recipe = Convert.ToString(collection["Recipe"]);
                    drinkProxy.CreateDrink(drink);

                    ViewBag.barId = ((DrinkIngredientViewModel)Session["createDrink"]).BarId;
                    string message = "Drinken er nu oprettet.";
                    return RedirectToAction("Index", new { barId = ViewBag.barId, message = message });
                }
                catch
                {
                    return View();
                }
            }
        }
    }
}

MixMixMVC/MixMixMVC/Controllers/OrderController.cs
using MixMixMVC.DrinkServiceReference;
using MixMixMVC.Helpers;
using MixMixMVC.Models;
using MixMixMVC.OrderServiceReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MixMixMVC.Controllers
{
    public class OrderController : Controller
    {
        /*
        OrderServiceClient orderProxy = new OrderServiceClient();
        DrinkServiceClient drinkProxy = new DrinkServiceClient();
        */

        [HttpPost]
        [AuthorizedLogin]
        public ActionResult AddToCart(int drinkid, int barid, string name, string ingredients)
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                DrinkServiceClient drinkProxy = serviceHelper.GetDrinkServiceClient();
                OrderServiceClient orderProxy = serviceHelper.GetOrderServiceClient();
                bool success = orderProxy.DecrementStock(drinkid, barid);
                string message;
                if (success)
                {
                    double price = drinkProxy.FindDrinkPriceById(drinkid, barid);
                    message = $"Drinken er købt til: {price} kr.";
                    if (Session["shoppingcart"] == null)
                    {
                        Session["shoppingcart"] = new List<OrderDrinkViewModel>();
                    }
                    List<OrderDrinkViewModel> list = (List<OrderDrinkViewModel>)Session["shoppingcart"];
                    List<OrderDrinkViewModel> drinkIdList = list.Where(x => x.DrinkId == drinkid).ToList();
                    if (!drinkIdList.Any())
                    {
                        OrderDrinkViewModel drink = new OrderDrinkViewModel();
                        drink.Names = new List<string>();
                        drink.BarId = barid;
                        drink.DrinkId = drinkid;
                        drink.Ingredients = ingredients;
                        drink.Names.Add(name);
                        drink.Subtotal = price;
                        drink.Quantity = 1;
                        ((List<OrderDrinkViewModel>)Session["shoppingcart"]).Add(drink);
                    }
                    else
                    {
                        if (!drinkIdList.First().Names.Contains(name))
                        {
                            drinkIdList.First().Names.Add(name);
                        }
                        drinkIdList.First().Subtotal += price;
                        drinkIdList.First().Quantity++;
                    }


                    return RedirectToAction("index", "drink", new { barId = barid, message = message });
                }
                else
                {
                    message = "drinken er desværre lige blevet udsolgt :(";
                    return RedirectToAction("index", "drink", new { barId = barid, message = message });
                }
            }
        }
        [AuthorizedLogin]
        public ActionResult ShoppingCart()
        {
            List<OrderDrinkViewModel> list = (List<OrderDrinkViewModel>)Session["shoppingcart"];
            return View(list);
        }
        [AuthorizedLogin]
        public ActionResult CreateOrder()
        {
            using (ServiceHelper serviceHelper = new ServiceHelper())
            {
                OrderServiceClient orderProxy = serviceHelper.GetOrderServiceClient();
                Order order = new Order();
                order.OrderLines = new List<OrderLine>();
                List<OrderDrinkViewModel> drinks = (List<OrderDrinkViewModel>)Session["shoppingcart"];
                foreach (OrderDrinkViewModel drink in drinks)
                {
                    OrderLine ol = new OrderLine
                    {
                        Drink = new OrderServiceReference.Drink { Id = drink.DrinkId },
                        Quantity = drink.Quantity,
                        Subtotal = drink.Subtotal,
                        Names = drink.Names,
                    };
                    order.OrderLines.Add(ol);
                    order.Status = Status.NotDone;
                    order.OrderTime = DateTime.Now;
                    order.Bar = new OrderServiceReference.Bar();
                    order.Bar.ID = drink.BarId;
                    order.Customer = new Customer();
                    order.Customer.Id = AuthHelper.CurrentUser.Id;
                }

                ViewBag.OrderNumber = orderProxy.CreateOrder(order);
                Session["shoppingcart"] = new List<OrderDrinkViewModel>();
                return View(ViewBag.OrderNumber);
            }
        }
    }
}

MixMixMVC/MixMixMVC/Views/Drink/Create.cshtml
@model MixMixMVC.Models.CreateDrinkViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>CreateDrinkViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DrinkName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DrinkName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DrinkName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="Ingredient row">
        <div class="form-horizontal">

            @Html.LabelFor(model => model.Ingredient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="ingredient" class="col-md-2">
                <div class="form-group">
                    @Html.EditorFor(model => model.Ingredient, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ingredient, "", new { @class = "text-danger" })
                </div>
            </div>


            @Html.LabelFor(model => model.Measurement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="measurement" class="col-md-1">
                <div class="form-group">
                    @Html.EditorFor(model => model.Measurement, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Measurement, "", new { @class = "text-danger" })
                </div>
            </div>


            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="quantity" class="col-md-1">
                <div class="form-group">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Decription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Decription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Decription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MixMixMVC/MixMixMVC/Views/Drink/DrinkDecription.cshtml
@model MixMixMVC.Models.DrinkDecriptionViewModel

@{
    ViewBag.Title = "DrinkDecription";
}
<div class="container">
    <div class="center_container">
        <h4>Opret drink - Side 3 af 3</h4>
        <hr />
        <p>
            Indtast en beskrivelse af fremgangsmåden <br />
            der bruges til at lave din drink
        </p>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="row">
                <div class="col-xs-12">
                    <p>Opskrift beskrivelse</p>
                </div>
                <div class="col-xs-12">
                    @Html.TextAreaFor(model => model.Recipe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Recipe, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-12">
                    <input type="submit" value="Færdiggør drink" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

MixMixMVC/MixMixMVC/Views/Drink/DrinkIngredient.cshtml
@model MixMixMVC.Models.DrinkIngredientViewModel

@{
    ViewBag.Title = "DrinkIngredient";
}
<div class="container">
    <div class="center_container">
        <h4>Opret drink - Side 2 af 3</h4>
        <hr />
        <p>
            Tilføj ingredienser til din drink, <br />
            fortsæt indtil du er færdig
        </p>
        <hr />
        <div class="row">
            <form action="@Url.Action("DrinkIngredient", "Drink")" method="post">
                <div class="col-xs-12">
                    <p>Ingrediens</p>
                </div>
                <div class="col-xs-12">
                    @Html.DropDownList("ddlIngredient", new SelectList(Model.Ingredients, "id", "Name"))
                </div>
                <div class="col-xs-12">
                    <p>Mål</p>
                </div>
                <div class="col-xs-12">
                    @Html.DropDownList("ddlMeasurement", new SelectList(Model.Measurements, "Id", "Type"))
                </div>

                <div class="col-xs-12">
                    <p>Mængde</p>
                </div>
                <div class="col-xs-12">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-12">
                    <button class="btn btn-success" type="submit">Tilføj ingrediens</button>
                </div>
                <div class="col-xs-12">
                    @Html.ActionLink("Tilføj opskrift", "DrinkDecription", null, new {@class="btn btn-success"})
                </div>
            </form>
        </div>
    </div>
</div>








@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>DrinkIngredientViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Ingredient, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ingredient, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ingredient, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Measurement, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Measurement, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Measurement, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

MixMixMVC/MixMixMVC/Views/Drink/DrinkName.cshtml
@model MixMixMVC.Models.DrinkNameViewModel

@{
    ViewBag.Title = "DrinkName";
}

<div class="container">
    <div class="center_container">
        <h4>Opret drink - Side 1 af 3</h4>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="row">
                    <div class="col-xs-12">
                        <p>Drinkens navn</p>
                    </div>
                    <div class="col-xs-12">
                        @Html.EditorFor(model => model.DrinkName, new { htmlAttributes = new { @class = "" } })
                        @Html.ValidationMessageFor(model => model.DrinkName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-12">
                        <input type="submit" value="Opret drinknavn" class="btn btn-success" />
                    </div>
                </div>
        }
    </div>
</div>

MixMixMVC/MixMixMVC/Views/Drink/Index.cshtml
@model Dictionary<int, MixMixMVC.DrinkServiceReference.DrinkViewModel>

@{
    ViewBag.Title = "Index";
}



<div class="container drink_list_container">
    <div class="row">
        <div class="drinklist_banner">
            <h2>Velkommen til @ViewBag.BarName</h2>

            <h3>@ViewBag.Message</h3>

            <p>
                @Html.ActionLink("Opret ny drink", "DrinkName", new { barId = (int)ViewBag.barId }, new { @class = "btn btn-primary" })
            </p>
        </div>
    </div>
    @if (Model.Count == 0)
    {
        <P>HER KAN MAN LAVE NOGET FEJL HÅNDTERING PÅ AT DRINKSKORTET ER TOMT</P>
    }
    else
    {
        <div class="row drink_list_header">
            <div class="col-xs-3">
                <p>Drinks:</p>
            </div>
            <div class="col-xs-5">
                <p>Indhold:</p>
            </div>
            <div class="col-xs-2">
                <p>Pris:</p>
            </div>
        </div>

        foreach (var item in Model.Values)
        {
            <div class="row drink_list_item">
                <form action="@Url.Action("AddToCart", "Order")" method="post">
                    <div class="col-xs-3">
                        @Html.DropDownList("name", new SelectList(item.Names))
                    </div>
                    <div class="col-xs-5">
                        <p>@Html.DisplayFor(modelItem => item.Ingredients)</p>
                    </div>
                    <div class="col-xs-2">
                        <p>@Html.DisplayFor(modelItem => item.Price)</p>
                    </div>
                    <div class="col-xs-2">
                        <button class="btn btn-success" style="margin-top:2px;" type="submit">Tilføj til kurv</button>
                    </div>

                    @Html.Hidden("ingredients", item.Ingredients)
                    @Html.Hidden("drinkId", item.Id)
                    @Html.Hidden("barId", (int)ViewBag.barId)
                </form>
            </div>
        }
    }
</div>